# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93e02121265b8f1771d221e3404f6e73ef103799ab7cdbc0019041791d2fefc9720ca316d0fd51012ec97c95b9f3fe3eaaf0bb39859d48b35c994377809ab76

test:
  secret_key_base: d15d856ec366cd365610c80047cbc226bbca730d3ec44f88a61620167d066021d978065465e87c55e8c578c6815c570735172fd2be76887b6b2356cd39d4ffdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
